### ISSUE TITLE
Ошибка создания пользователя всегда отдаётся в html

### ISSUE THREAD

**Issue by monshq** [ArtemGuschin8876/GameMasterWeb#6]
Делаю запрос к апи:

```
❯ http POST localhost:4000/users Accept:application/json name=asdf
HTTP/1.1 200 OK
Content-Type: text/html; charset=utf-8
Date: Thu, 04 Jul 2024 17:34:41 GMT
Transfer-Encoding: chunked

<!DOCTYPE html>
<html lang="en">
...
```

Мне отдаётся html, хотя в заголовках указан Accept: application/json.

**Comment by ArtemGuschin8876** [comment]
Я вроде исправил это, и создал новую ветку с ПР, немного не пойму куда писать теперь) А еще момент с CI вроде делаю по доке в yaml файле, но CI не падает при наличии ошибок форматирования, буду рад узнать проблему)
